/*
    Generated by Atomist on 06 07 2016 
*/
package com.example.urlBuilder;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.test.context.web.WebAppConfiguration;
import org.springframework.boot.test.SpringApplicationConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;

@RunWith(SpringJUnit4ClassRunner.class)
@SpringApplicationConfiguration(classes = UrlBuilderApplication.class)
@WebAppConfiguration
public class UrlBuilderApplicationTests {

	@Test
	public void contextLoads() {
	}
}
