/*
    Generated by Atomist on 06 07 2016 
*/
package com.example.urlBuilder;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class UrlBuilderApplication {

    public static void main(String[] args) {
        SpringApplication.run(UrlBuilderApplication.class, args);
    }
}
