/*
    Generated by Atomist on 06 07 2016 
*/
package com.example.urlBuilder;

import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

/**
* Spring Java configuration file for UrlBuilder.
* Don't even think of using XML.
*/
@Configuration
public class UrlBuilderConfiguration {

    // Your beans go here ... 
	// Atomist Bot suggests "maybe use an Atomist project editor to add a sample one?"
}
